apiVersion: v1
kind: Service
metadata:
  name: server-stable
  labels:
    app.kubernetes.io/component: game-server
    color-turf/release-channel: stable
spec:
  selector:
    app.kubernetes.io/name: paint-arena-game-api
  ports:
    - name: http
      port: 3001
      targetPort: http
