global:
  scrape_interval: 2s

scrape_configs:
  - job_name: color-turf-stable
    static_configs:
      - targets: ["server-stable:3001"]

  - job_name: color-turf-dr
    static_configs:
      - targets: ["server-dr:3001"]
