apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "color-turf.fullname" . }}-web
  labels:
    {{- include "color-turf.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "color-turf.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: web
        app.kubernetes.io/version: {{ .Values.server.version | quote }}
        color-turf/release-channel: stable
        color-turf/cluster-role: {{ .Values.server.clusterName | quote }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - { name: http, containerPort: 8080 }
          livenessProbe:
            httpGet: { path: /admin, port: http }
          readinessProbe:
            httpGet: { path: /admin, port: http }
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
